version: "3.8"

services:
  cvs-expensetracker-api:
    image: cvs-expensetracker-api:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7114:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      ASPNETCORE_URLS: "${ASPNETCORE_URLS}"
      Authentication__Audience: "${Authentication__Audience}"
      Authentication__Issuer: "${Authentication__Issuer}"
      Authentication__MetadataAddress: "${Authentication__MetadataAddress}"
      Authentication__RequireHttpsMetadata: "${Authentication__RequireHttpsMetadata}"
      ConnectionStrings__SqlDatabase: "${ConnectionStrings__SqlDatabase}"
      Kestrel__Certificates__Default__Password: "${Kestrel__Certificates__Default__Password}"
      Kestrel__Certificates__Default__Path: "${Kestrel__Certificates__Default__Path}"
    volumes:
      - "${CERT_VOLUME}:/https-certs:ro"
    depends_on:
      - sqlserver
      - keycloak
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command: start-dev
    ports:
      - "7110:8080"
    environment:
      KC_DB: mssql
      KC_DB_URL: "${Keycloak_DatabaseConnection}"
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: "${SA_PASSWORD}"
      KC_BOOTSTRAP_ADMIN_USERNAME: "${Keycloak_Username}"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${Keycloak_Password}"
    depends_on:
      - sqlserver

volumes:
  sqlserver_data: