version: '3.8'
services:
  cvs-expensetracker-api:
    image: cvs-expensetracker-api:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7114:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
    volumes:
      - ${CERT_VOLUME}:/https