name: Main Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PATH_TO_GLOBAL_JSON: "./global.json"
  PATH_TO_MAIN_PROJECT: "./src/CabaVS.ExpenseTracker.API/CabaVS.ExpenseTracker.API.csproj"
  PATH_INTEGRATION_TESTS: "./tests/CabaVS.ExpenseTracker.IntegrationTests/CabaVS.ExpenseTracker.IntegrationTests.csproj"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main-environment
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ${{ env.PATH_TO_GLOBAL_JSON }}

      - name: Restore solution
        run: dotnet restore ${{ env.PATH_TO_MAIN_PROJECT }}

      - name: Build solution
        run: dotnet build ${{ env.PATH_TO_MAIN_PROJECT }} --configuration Release --no-restore
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: artifacts/build

  test:
    runs-on: ubuntu-latest
    environment: main-environment
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ${{ env.PATH_TO_GLOBAL_JSON }}  
      
      - name: Run Integration Tests
        run: dotnet test ${{ env.PATH_INTEGRATION_TESTS }} --configuration Release