name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "8.x"
  PATH_SLN: "./CabaVS.ExpenseTracker.sln"
  PATH_INTEGRATION_TESTS: "./tests/CabaVS.ExpenseTracker.IntegrationTests/CabaVS.ExpenseTracker.IntegrationTests.csproj"
  PATH_BACKEND_PROJECT_PATH: './src/CabaVS.ExpenseTracker.API/CabaVS.ExpenseTracker.API.csproj'
  PATH_BACKEND_OUTPUT: './built-backend'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: et-dev
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PATH_SLN }}

      - name: Build
        run: dotnet build ${{ env.PATH_SLN }} --configuration Release --no-restore

      - name: Integration Tests
        env:
          Auth__ApiKey: ${{ secrets.APIKEY }}
        run: dotnet test ${{ env.PATH_INTEGRATION_TESTS }} --configuration Release --no-restore --no-build
        
      - name: Publish Backend
        run: dotnet publish ${{ env.PATH_BACKEND_PROJECT_PATH }} --configuration Release --no-restore --no-build --output ${{ env.PATH_BACKEND_OUTPUT }}
      
      - name: Publish Backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: ${{ env.PATH_BACKEND_OUTPUT }}

      - name: logout
        run: az logout